#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bash /home/frogget/.config/polybar/launch.sh &
nitrogen --restore &
picom &
conky &
bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          10

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#595B82"
bspc config normal_border_color "#1f1f1f"
bspc config active_border_color "#007e7a"
bspc config focused_border_color "#007e7a"
