#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bash /home/frogget/.config/polybar/launch.sh --material &
nitrogen --restore &
flatpak run io.github.jeffshee.Hidamari & 
picom &
conky &
bspc monitor -d I II III IV V VI VII

bspc config border_width         1
bspc config window_gap          12

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#595B82"
bspc config normal_border_color "#1f1f1f"
bspc config active_border_color "#007e7a"
bspc config focused_border_color "#007e7a"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#$HOME/.config/polybar/launch.sh
#$HOME/.config/nitrogen/launch.sh

